### ISSUE TITLE
`rad patch` throws `Patch::author: at least one revision is present`

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/heartwood#350]
When following the instructions to create a patch with the following example https://github.com/radicle-dev/heartwood/blob/master/radicle-cli/examples/rad-patch.md

The patch creation works fine

```
➜  patch-tests git:(master) rad patch open

🌱 Creating patch for patch-tests

ok Looking for HEAD (f5afe97) in storage...
ok Analyzing remotes...

z6MkhfNHyujNn6Rrhc74AhyTboVyinvLHs6wxntuRA6S9h2u/master (6cc8889) <- z6MkmzR…ymd6fz6/master (f5afe97)
1 commit(s) ahead, 0 commit(s) behind

f5afe97 Add some text to readme


╭─ Add some text to readme ───────

Here goes the patch description

Will try to write some markdown

# A title

## Some subtitles

- lists
- of
- items

╰─────────────────────────────────

 ⤷ Continue? yes

ok Patch ef76cc741530270740812c0a086614b66e9e2d31 created 🌱
```

But if I want to see the created patch with `rad patch` I get the following error output
It seems it is somehow related to having a description that has multiple lines of description, since a patch with only one line works fine

```
➜  patch-tests git:(master) rad patch
thread 'main' panicked at 'Patch::author: at least one revision is present', radicle/src/cob/patch.rs:197:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:135:5
   3: core::panicking::panic_str
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:119:5
   4: core::option::expect_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:1879:5
   5: core::option::Option<T>::expect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:741:21
   6: radicle::cob::patch::Patch::author
             at /home/sebastinez/projects/heartwood/radicle/src/cob/patch.rs:193:10
   7: radicle_cli::commands::rad_patch::list::run
             at /home/sebastinez/projects/heartwood/radicle-cli/src/commands/patch/list.rs:35:12
   8: radicle_cli::commands::rad_patch::run
             at /home/sebastinez/projects/heartwood/radicle-cli/src/commands/patch.rs:203:13
   9: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
  10: <F as radicle_cli::terminal::Command<A,C>>::run
             at /home/sebastinez/projects/heartwood/radicle-cli/src/terminal.rs:57:9
  11: radicle_cli::terminal::run_command_args
             at /home/sebastinez/projects/heartwood/radicle-cli/src/terminal.rs:114:11
  12: rad::run_other
             at /home/sebastinez/projects/heartwood/radicle-cli/src/main.rs:218:13
  13: rad::run
             at /home/sebastinez/projects/heartwood/radicle-cli/src/main.rs:93:17
  14: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
  15: core::result::Result<T,E>::and_then
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1372:22
  16: rad::main
             at /home/sebastinez/projects/heartwood/radicle-cli/src/main.rs:22:11
  17: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sebastinez** [comment]
Duplicate of #351
