### ISSUE TITLE
OLPC library for serializing the data ignores escaping newlines (and other control characters)

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/heartwood#351]
When trying to create an issue with multiline and then trying to fetch it I get the following error log.
I think it is somehow related with #350 

```
thread 'tokio-runtime-worker' panicked at 'Issue::author: at least one comment is present', radicle/src/cob/issue.rs:177:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:135:5
   3: core::panicking::panic_str
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:119:5
   4: core::option::expect_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:1879:5
   5: core::option::Option<T>::expect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:741:21
   6: radicle::cob::issue::Issue::author
             at ./radicle/src/cob/issue.rs:173:9
   7: radicle_httpd::api::json::issue
             at ./radicle-httpd/src/api/json.rs:95:19
   8: radicle_httpd::api::v1::projects::issues_handler::{{closure}}::{{closure}}
             at ./radicle-httpd/src/api/v1/projects.rs:399:31
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:629:13
  10: core::option::Option<T>::map
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:925:29
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/iter/adapters/map.rs:103:9
  12: <core::iter::adapters::skip::Skip<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/iter/adapters/skip.rs:38:13
  13: <core::iter::adapters::take::Take<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/iter/adapters/take.rs:37:13
  14: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/mod.rs:2848:35
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/spec_extend.rs:17:9
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  17: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/in_place_collect.rs:167:20
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/mod.rs:2748:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/iter/traits/iterator.rs:1836:9
  20: radicle_httpd::api::v1::projects::issues_handler::{{closure}}
             at ./radicle-httpd/src/api/v1/projects.rs:395:18
  21: <F as axum::handler::Handler<(M,T1,T2,T3),S,B>>::call::{{closure}}
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/handler/mod.rs:213:52
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  24: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  25: <axum::handler::future::IntoServiceFuture<F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/macros.rs:42:17
  26: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  27: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  28: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  29: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  30: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  31: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  32: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  33: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  34: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/routing/route.rs:164:61
  35: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  36: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  37: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  38: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  39: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  40: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  41: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  42: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  43: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/routing/route.rs:164:61
  44: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  45: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  46: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  47: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  48: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  49: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  50: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  51: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  52: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/routing/route.rs:164:61
  53: <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.5/src/cors/mod.rs:663:56
  54: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  55: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  56: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  57: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  58: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  59: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  60: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  61: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  62: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  63: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  64: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  65: <tower::util::map_err::MapErrFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  66: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  67: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  68: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  69: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  70: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  71: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  72: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  73: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  74: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/routing/route.rs:164:61
  75: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  76: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  77: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  78: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  79: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  80: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  81: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  82: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  83: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.7/src/routing/route.rs:164:61
  84: <F as futures_core::future::TryFuture>::try_poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  85: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  86: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  87: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  88: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  89: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  90: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  91: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/sebastinez/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by FintanH** [comment]
Digging into this to see what I can find. I can confirm that the information is at least preserved.

```
haptop in ~/TestRad/storage/z4AbusZizKhtYPWHxJwdzJGEAhqKA on master λ git cat-file -p 48afad2256fbb819c8c636a6f11e7e923d27f5eb
tree ea8664a55e8fbfaa21f25d30d5a828c79c8d8214
parent e338353f58e6f3a8d9f986761b3dd0cfc005e10d
author radicle <radicle@localhost> 1677146428 +0000
committer radicle <radicle@localhost> 1677146428 +0000
gpgsig -----BEGIN SSH SIGNATURE-----
 U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgIAiQaJMhsjsAXYNUYuYT1pUUgF
 g94U+5IQ+s5l8Oh30AAAAHcmFkaWNsZQAAAAAAAAAGc2hhMjU2AAAAUwAAAAtzc2gtZWQy
 NTUxOQAAAEC3xUN/TWQ7ZYeJyBwp5/woTaxYBZ4QTVUQ+vB8eIueKXXNTgXk2PXBLOe1Dg
 nizp+4604HtM9j9eaIEjftpzMK
 -----END SSH SIGNATURE-----

Create issue

Rad-Resource: e338353f58e6f3a8d9f986761b3dd0cfc005e10d
                                                                      
haptop in ~/TestRad/storage/z4AbusZizKhtYPWHxJwdzJGEAhqKA on master λ git cat-file -p ea8664a55e8fbfaa21f25d30d5a828c79c8d8214
100644 blob 61c361be723eabaabacf52b5eed6688a29e4599a	0
100644 blob e8367961e393bc7480ade6e22a9d6f3f99d50c66	1
100644 blob a2c22e996b7cb9013fd8f719c656c2473597cc47	2
100644 blob 140944f33308458f505989cfba134058257ae8e4	3
100644 blob 30c87173f42e65865ed83a7917827a9814739e1a	manifest
                                                                    
haptop in ~/TestRad/storage/z4AbusZizKhtYPWHxJwdzJGEAhqKA on master λ git cat-file -p 61c361be723eabaabacf52b5eed6688a29e4599a
{"action":{"body":"Trying to test what happens
with newlines of text

Let's go!","replyTo":null,"type":"comment"},"type":"thread"}

haptop in ~/TestRad/storage/z4AbusZizKhtYPWHxJwdzJGEAhqKA on master λ git cat-file -p e8367961e393bc7480ade6e22a9d6f3f99d50c66
{"add":[],"remove":[],"type":"assign"}

haptop in ~/TestRad/storage/z4AbusZizKhtYPWHxJwdzJGEAhqKA on master λ git cat-file -p a2c22e996b7cb9013fd8f719c656c2473597cc47
{"title":"Totally New","type":"edit"}

haptop in ~/TestRad/storage/z4AbusZizKhtYPWHxJwdzJGEAhqKA on master λ git cat-file -p 140944f33308458f505989cfba134058257ae8e4
{"add":[],"remove":[],"type":"tag"}
```

So it must be down to the reading back of information because:
```
RAD_HOME=/home/haptop/TestRad rad issue show 48afad2256fbb819c8c636a6f11e7e923d27f5eb
title: 
state: open
tags: 
assignees:
```
is no bueno...

**Comment by FintanH** [comment]
Can confirm that there's a bug adding a test case in `cob/issue.rs`:

```rust
    #[test]
    fn test_issue_multilines() {
        let tmp = tempfile::tempdir().unwrap();
        let (_, signer, project) = test::setup::context(&tmp);
        let mut issues = Issues::open(*signer.public_key(), &project).unwrap();
        let created = issues
            .create(
                "My first issue",
                "Blah blah blah.\nYah yah yah",
                &[],
                &[],
                &signer,
            )
            .unwrap();

        assert_eq!(created.clock().get(), 4);

        let (id, created) = (created.id, created.issue);
        let issue = issues.get(&id).unwrap().unwrap();

        assert_eq!(created, issue);
        assert_eq!(issue.title(), "My first issue");
        assert_eq!(issue.author(), issues.author());
        assert_eq!(issue.description(), Some("Blah blah blah.\nYah yah yah"));
        assert_eq!(issue.comments().count(), 1);
        assert_eq!(issue.state(), &State::Open);
    }
```

```
running 1 test
test cob::issue::test::test_issue_multilines ... FAILED

failures:

---- cob::issue::test::test_issue_multilines stdout ----
thread 'cob::issue::test::test_issue_multilines' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
>My first issue
```

**Comment by FintanH** [comment]
Our culprit seems to be to do with deserializing the `Action` [here](https://github.com/radicle-dev/heartwood/blob/master/radicle/src/cob/op.rs#L169).

We get the following error:
```
Error("control character (\\u0000-\\u001F) found while parsing a string", line: 2, column: 0)
```
which is being logged but the issue appears back empty because we initialize the `traverse` with a default state.

**Comment by FintanH** [comment]
lol, fun!

https://docs.rs/olpc-cjson/0.1.2/olpc_cjson/

> OLPC’s canonical JSON specification is subtly different from other “canonical JSON” specifications, and is also not a strict subset of JSON (specifically, ASCII control characters 0x00–0x1f are printed literally, which is not valid JSON). Therefore, serde_json cannot necessarily deserialize JSON produced by this formatter.

**Comment by FintanH** [comment]
:heart: 

https://github.com/radicle-dev/radicle-link/blob/master/link-canonical/src/formatter.rs#L13-L33

I think we should port over `link-canonical` since I believe it does The Right Thing:tm:
