### ISSUE TITLE
thread panicked at 'Wire::upgraded: peer write buffer not empty on upgrade', /workdir/radicle-node/src/wire/protocol.rs:374:23

### ISSUE THREAD

**Issue by adaszko** [radicle-dev/heartwood#503]
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: radicle_node::wire::protocol::Wire<R,S,W,G>::upgraded
             at /workdir/radicle-node/src/wire/protocol.rs:374:23
   3: <radicle_node::wire::protocol::Wire<R,S,W,G> as reactor::reactor::Handler>::handover_transport
             at /workdir/radicle-node/src/wire/protocol.rs:665:25
   4: reactor::reactor::Runtime<H,P>::handle_action
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.1.1/src/reactor.rs:734:17
   5: reactor::reactor::Runtime<H,P>::handle_actions
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.1.1/src/reactor.rs:674:31
   6: reactor::reactor::Runtime<H,P>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.1.1/src/reactor.rs:571:13
   7: reactor::reactor::Reactor<C>::with::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.1.1/src/reactor.rs:315:13
```

Viewable at https://logs.radicle.garden/d/PwDPrkG4k/home?orgId=1&viewPanel=12&from=1680179940000&to=1680179942000

**Comment by cloudhead** [comment]
```
DEBUG service  Fetch requested for rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5 from z6MkeyKLd5BErS74GPvZDv2S6rU8nF5zheNKx72CYwgSR52G..
DEBUG service  Write FetchOk(rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5) to z6MkeyKLd5BErS74GPvZDv2S6rU8nF5zheNKx72CYwgSR52G [inbound connected <gossip>]
DEBUG wire     Requesting transport handover from reactor for peer (fd=12)
ERROR wire     Error during writing to peer 12: Resource temporarily unavailable (os error 11)
DEBUG wire     Received transport handover (fd=12)
DEBUG wire     Peer z6MkeyKLd5BErS74GPvZDv2S6rU8nF5zheNKx72CYwgSR52G upgraded for fetch rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5
	
thread 'z6MksmpU5b1dS7oaqF2bHXhQi1DWy2hB7Mh9CuN7y1DN6QSz' panicked at 'Wire::upgraded: peer write buffer not empty on upgrade', /workdir/radicle-node/src/wire/protocol.rs:374:23

```

**Comment by cloudhead** [comment]
This code was removed.
